/**
 * Get List
 */
export const WEB_JOURNAL_CATEGORY_LIST = "WEB_JOURNAL_CATEGORY_LIST";
export const WEB_JOURNAL_CATEGORY_LIST_SUCCESS = "WEB_JOURNAL_CATEGORY_LIST_SUCCESS";
export const WEB_JOURNAL_CATEGORY_LIST_FAILURE = "WEB_JOURNAL_CATEGORY_LIST_FAILURE";
